import { 
  LucideIcon,
  Phone,
  Mail,
  MapPin,
  Clock,
  Calendar,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Menu,
  X,
  Star,
  Heart,
  Share2,
  Facebook,
  Instagram,
  Twitter,
  MessageCircle,
  Navigation,
  Car,
  Plane,
  Beer,
  Utensils,
  PartyPopper,
  Trophy,
  Target,
  DollarSign,
  Sparkles,
  Info,
  AlertCircle,
  CheckCircle,
  XCircle,
  Loader2,
  ExternalLink,
  Copy,
  Search,
  Filter,
  User,
  Users,
  Building,
  Gift,
  Music,
  Mic,
  Camera,
  Image,
  Play,
  Pause,
  Volume2,
  Wifi,
  ParkingCircle,
  Dog,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Wind,
  Thermometer,
  Zap,
  Coffee,
  Wine,
  Pizza,
  Home,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Download,
  Upload,
  RefreshCw,
  RotateCw,
  Plus,
  Minus,
  Edit,
  Trash2,
  Save,
  FileText,
  Folder,
  Grid,
  List,
  LayoutGrid,
  Maximize2,
  Minimize2,
  ZoomIn,
  ZoomOut,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Shield,
  ShieldCheck,
  Bell,
  BellOff,
  Bookmark,
  Tag,
  Tags,
  Hash,
  Link,
  Unlink,
  Paperclip,
  Send,
  Inbox,
  Archive,
  Trash,
  Flag,
  MoreHorizontal,
  MoreVertical,
  Settings,
  HelpCircle,
  LogIn,
  LogOut,
  UserPlus,
  UserMinus,
  UserCheck,
  CreditCard,
  Wallet,
  Receipt,
  ShoppingCart,
  ShoppingBag,
  Package,
  Truck,
  Globe,
  Map as MapIcon,
  Compass,
  Watch,
  Smartphone,
  Monitor,
  Tv,
  Radio,
  Headphones,
  Mic2,
  Video,
  Film,
  Award,
  Medal,
  Crown,
  Flame,
  Lightbulb,
  Book,
  BookOpen,
  Newspaper,
  PenTool,
  Palette,
  Brush,
  Scissors,
  Ruler,
  Calculator,
  Briefcase,
  Presentation,
  BarChart,
  LineChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  Activity,
  Percent,
  Hash as Hashtag,
  AtSign,
  Copyright,
  Smile,
  Frown,
  Meh,
  ThumbsUp,
  ThumbsDown,
  MessageSquare,
  MessagesSquare,
  Quote,
  type LucideProps
} from 'lucide-react'
import { forwardRef } from 'react'
import { cn } from '@/lib/utils'

// Map common icon names to Lucide components
const iconMap = {
  // Contact & Communication
  phone: Phone,
  mail: Mail,
  email: Mail,
  location: MapPin,
  mapPin: MapPin,
  message: MessageCircle,
  chat: MessageCircle,
  share: Share2,
  send: Send,
  inbox: Inbox,
  
  // Navigation & Directions
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  menu: Menu,
  close: X,
  navigation: Navigation,
  compass: Compass,
  map: MapIcon,
  
  // Time & Calendar
  clock: Clock,
  time: Clock,
  calendar: Calendar,
  date: Calendar,
  watch: Watch,
  
  // Social Media
  facebook: Facebook,
  instagram: Instagram,
  twitter: Twitter,
  
  // Transport
  car: Car,
  plane: Plane,
  airplane: Plane,
  truck: Truck,
  parking: ParkingCircle,
  
  // Food & Drink
  beer: Beer,
  drink: Beer,
  food: Utensils,
  utensils: Utensils,
  wine: Wine,
  coffee: Coffee,
  pizza: Pizza,
  
  // Entertainment & Events
  party: PartyPopper,
  celebration: PartyPopper,
  music: Music,
  mic: Mic,
  microphone: Mic2,
  play: Play,
  pause: Pause,
  volume: Volume2,
  camera: Camera,
  image: Image,
  video: Video,
  film: Film,
  
  // Awards & Achievement
  star: Star,
  trophy: Trophy,
  award: Award,
  medal: Medal,
  crown: Crown,
  target: Target,
  
  // Business & Finance
  dollar: DollarSign,
  money: DollarSign,
  creditCard: CreditCard,
  wallet: Wallet,
  receipt: Receipt,
  briefcase: Briefcase,
  building: Building,
  
  // Features & Amenities
  wifi: Wifi,
  dog: Dog,
  petFriendly: Dog,
  gift: Gift,
  sparkles: Sparkles,
  flame: Flame,
  fire: Flame,
  
  // UI States & Actions
  info: Info,
  alert: AlertCircle,
  warning: AlertCircle,
  success: CheckCircle,
  check: CheckCircle,
  error: XCircle,
  loading: Loader2,
  spinner: Loader2,
  external: ExternalLink,
  copy: Copy,
  search: Search,
  filter: Filter,
  edit: Edit,
  delete: Trash2,
  trash: Trash2,
  save: Save,
  download: Download,
  upload: Upload,
  refresh: RefreshCw,
  rotate: RotateCw,
  plus: Plus,
  add: Plus,
  minus: Minus,
  remove: Minus,
  
  // Users & Accounts
  user: User,
  users: Users,
  group: Users,
  userPlus: UserPlus,
  userMinus: UserMinus,
  userCheck: UserCheck,
  login: LogIn,
  logout: LogOut,
  
  // Layout & View
  grid: Grid,
  list: List,
  layoutGrid: LayoutGrid,
  maximize: Maximize2,
  minimize: Minimize2,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  eye: Eye,
  eyeOff: EyeOff,
  
  // Security & Privacy
  lock: Lock,
  unlock: Unlock,
  shield: Shield,
  shieldCheck: ShieldCheck,
  
  // Notifications & Flags
  bell: Bell,
  bellOff: BellOff,
  notification: Bell,
  bookmark: Bookmark,
  flag: Flag,
  tag: Tag,
  tags: Tags,
  hash: Hash,
  hashtag: Hashtag,
  
  // Links & Attachments
  link: Link,
  unlink: Unlink,
  paperclip: Paperclip,
  attachment: Paperclip,
  
  // Shopping
  cart: ShoppingCart,
  shoppingCart: ShoppingCart,
  bag: ShoppingBag,
  shoppingBag: ShoppingBag,
  package: Package,
  
  // Weather
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  rain: CloudRain,
  wind: Wind,
  thermometer: Thermometer,
  
  // Misc
  heart: Heart,
  home: Home,
  globe: Globe,
  zap: Zap,
  lightbulb: Lightbulb,
  book: Book,
  bookOpen: BookOpen,
  newspaper: Newspaper,
  file: FileText,
  folder: Folder,
  settings: Settings,
  help: HelpCircle,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  at: AtSign,
  copyright: Copyright,
  smile: Smile,
  frown: Frown,
  meh: Meh,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  quote: Quote,
  
  // Charts & Analytics
  barChart: BarChart,
  lineChart: LineChart,
  pieChart: PieChart,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  activity: Activity,
  percent: Percent,
  
  // Creative Tools
  pen: PenTool,
  palette: Palette,
  brush: Brush,
  scissors: Scissors,
  ruler: Ruler,
  calculator: Calculator,
  presentation: Presentation
} as const

export type IconName = keyof typeof iconMap

interface IconProps extends Omit<LucideProps, 'ref'> {
  name: IconName
}

export const Icon = forwardRef<SVGSVGElement, IconProps>(
  ({ name, className, ...props }, ref) => {
    const IconComponent = iconMap[name]
    
    if (!IconComponent) {
      console.warn(`Icon "${name}" not found in icon map`)
      return null
    }
    
    return (
      <IconComponent
        ref={ref}
        className={cn('h-5 w-5', className)}
        {...props}
      />
    )
  }
)

Icon.displayName = 'Icon'

// Export specific icons for direct usage
export {
  Phone as PhoneIcon,
  Mail as MailIcon,
  MapPin as LocationIcon,
  Clock as ClockIcon,
  Calendar as CalendarIcon,
  ChevronRight as ChevronRightIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronDown as ChevronDownIcon,
  ChevronUp as ChevronUpIcon,
  Menu as MenuIcon,
  X as CloseIcon,
  Star as StarIcon,
  Heart as HeartIcon,
  Share2 as ShareIcon,
  Beer as BeerIcon,
  Utensils as FoodIcon,
  PartyPopper as PartyIcon,
  Car as CarIcon,
  Plane as PlaneIcon,
  Wifi as WifiIcon,
  Dog as DogIcon,
  Gift as GiftIcon,
  Trophy as TrophyIcon,
  Target as TargetIcon,
  DollarSign as DollarIcon,
  Info as InfoIcon,
  AlertCircle as AlertIcon,
  CheckCircle as CheckIcon,
  XCircle as ErrorIcon,
  Loader2 as LoadingIcon,
  Search as SearchIcon,
  Filter as FilterIcon,
  User as UserIcon,
  Users as UsersIcon,
  Settings as SettingsIcon,
  HelpCircle as HelpIcon
}

// Convenience function to get icon by name
export function getIcon(name: IconName): LucideIcon | null {
  return iconMap[name] || null
}